# Numpy

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Data/iris.csv')
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [5]:
iris_data_numerical = df.select_dtypes(include=['float64', 'int64']).values
iris_data_numerical

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

### Numpy Array

In [6]:
# 1 Dimentional Array
python_list = [1, 2, 3, 4, 5]
array = np.array(python_list)
print(array)
print(python_list)

[1 2 3 4 5]
[1, 2, 3, 4, 5]

In [7]:
array[1]

2

In [8]:
# np.zeros()
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# np.ones()
ones_array = np.ones((3, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# np.arange() start, stop, step
arange_array = np.arange(0, 10, 2)
arange_array

array([0, 2, 4, 6, 8])

### Random value numpy array
- np.random.rand() -> random float
- np.random.randint() -> random int

In [11]:
random_float_array = np.random.rand(3,3)
random_float_array

array([[0.65593704, 0.09143331, 0.44647283],
       [0.38255646, 0.5761324 , 0.1400855 ],
       [0.56231257, 0.68353164, 0.53468941]])

In [12]:
random_int_array = np.random.randint(0, 100, size=(3, 3), dtype='int64')
random_int_array

array([[ 5, 58,  7],
       [90,  8, 87],
       [29, 96, 95]], dtype=int64)

# Reshaping Array

In [13]:
# matrix multiplication
old_array = np.arange(1, 10)
old_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
old_array_reshaped = old_array.reshape(3, 3)
old_array_reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# indexing dan slicing [start:stop:step]
iris_data_numerical[1,  2]

1.4

In [16]:
# [row, column] -> [start:stop:step, start:stop:step]
iris_data_numerical[0:5, 0:2]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [17]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [18]:
_gt_5 = iris_data_numerical[iris_data_numerical[:, 0] > 5.0]
_gt_5

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

# Operasi Numpy (Aritmatika & Aggregasi)

In [19]:
data1_5 = np.arange(1, 6)
data5_10 = np.arange(6, 11)

In [20]:
data_sum = data1_5 + data5_10
data_sum

array([ 7,  9, 11, 13, 15])

In [21]:
data_substract = data5_10 - data1_5
data_substract

array([5, 5, 5, 5, 5])

In [22]:
data = np.random.randint(10, 100, size=(3, 3))
data

array([[15, 18, 24],
       [29, 56, 70],
       [14, 65, 34]])

- import math as m
- data_sqrt = m.sqrt(data)
- data_sqrt

gabisa karena math hanya bisa menghandle satu list

In [23]:
# np.sqrt()
data_sqrt = np.sqrt(data)
data_sqrt

array([[3.87298335, 4.24264069, 4.89897949],
       [5.38516481, 7.48331477, 8.36660027],
       [3.74165739, 8.06225775, 5.83095189]])

In [24]:
# np.log()
data_log = np.log(data)
data_log

array([[2.7080502 , 2.89037176, 3.17805383],
       [3.36729583, 4.02535169, 4.24849524],
       [2.63905733, 4.17438727, 3.52636052]])

In [25]:
# np.exp(), np.sin(), np.cos(), np.tan()

### Dot product & Matrix Multiplication
- Dot product → operasi antara dua vektor yang menghasilkan satu nilai skalar (example: 2)
- Matrix multiplication → menghitung banyak dot product sekaligus -- wajib (m x n ; n x p) hasilnya m x p

In [26]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [27]:
# np.dot = dot product
hasil_dot = np.dot(v1, v2)  
hasil_dot

32

In [28]:
m1 = np.array([[2, 3, 1],
               [7, 6, 1]])
m2 = np.array([[1, 2],
                [5, 3],
                [1, 1]])

In [29]:
hasil_multiplication = np.dot(m1, m2)
hasil_multiplication

array([[18, 14],
       [38, 33]])

In [30]:
hasil_multiplication = np.matmul(m1, m2)
hasil_multiplication

array([[18, 14],
       [38, 33]])

# Broadcasting

In [31]:
# kasus vektor dan skalar
v = np.array([1, 2, 3])
s = 10

hasil = v + s
hasil

array([11, 12, 13])

In [32]:
# kasus matrix dan vektor
# untuk bisa mengoprasikan jumlah v harus sama dengan baris atau kolom m

m = np.array([[1, 2, 3],
             [4, 5, 6]])
v = np.array([10, 20, 30])

m = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([[10], 
              [30]])

hasil = m + v
hasil

array([[11, 12, 13],
       [34, 35, 36]])

In [33]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [34]:
iris_data_numerical_tambahan = iris_data_numerical[:, 3] + 0.5
iris_data_numerical_tambahan

array([0.7, 0.7, 0.7, 0.7, 0.7, 0.9, 0.8, 0.7, 0.7, 0.6, 0.7, 0.7, 0.6,
       0.6, 0.7, 0.9, 0.9, 0.8, 0.8, 0.8, 0.7, 0.9, 0.7, 1. , 0.7, 0.7,
       0.9, 0.7, 0.7, 0.7, 0.7, 0.9, 0.6, 0.7, 0.6, 0.7, 0.7, 0.6, 0.7,
       0.7, 0.8, 0.8, 0.7, 1.1, 0.9, 0.8, 0.7, 0.7, 0.7, 0.7, 1.9, 2. ,
       2. , 1.8, 2. , 1.8, 2.1, 1.5, 1.8, 1.9, 1.5, 2. , 1.5, 1.9, 1.8,
       1.9, 2. , 1.5, 2. , 1.6, 2.3, 1.8, 2. , 1.7, 1.8, 1.9, 1.9, 2.2,
       2. , 1.5, 1.6, 1.5, 1.7, 2.1, 2. , 2.1, 2. , 1.8, 1.8, 1.8, 1.7,
       1.9, 1.7, 1.5, 1.8, 1.7, 1.8, 1.8, 1.6, 1.8, 3. , 2.4, 2.6, 2.3,
       2.7, 2.6, 2.2, 2.3, 2.3, 3. , 2.5, 2.4, 2.6, 2.5, 2.9, 2.8, 2.3,
       2.7, 2.8, 2. , 2.8, 2.5, 2.5, 2.3, 2.6, 2.3, 2.3, 2.3, 2.6, 2.1,
       2.4, 2.5, 2.7, 2. , 1.9, 2.8, 2.9, 2.3, 2.3, 2.6, 2.9, 2.8, 2.4,
       2.8, 3. , 2.8, 2.4, 2.5, 2.8, 2.3])

### np.concatenate
mengabungkan 2 array  
axis = 0 - (rows)  
axis = 1 - (columns)

In [35]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

array_gabungan = np.concatenate((array1, array2), axis=0)
array_gabungan

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5],
                   [6]])

array_gabungan = np.concatenate((array1, array2), axis=1)
array_gabungan

array([[1, 2, 5],
       [3, 4, 6]])